const data = [
  {
    name: "Aceh",
    title: "Sultan",
    rumah: "Rumoh Aceh",
    pakaian: "Ulee Balang",
    musik: "Seudati, Rapai",
    tari: "Tari Saman, Tari Seudati",
    senjata: "Rencong",
    bahasa: "Aceh",
    imgUrl: "URL_RUMAH_TRADISIONAL_ACEH",
    coordinates: [95.4192, 5.5544], // Aceh
  },
  {
    name: "Sumatera Utara",
    title: "Raja",
    rumah: "Bolon",
    pakaian: "Ulos",
    musik: "Gondang",
    tari: "Tari Tor-Tor",
    senjata: "Piso Gaja Dombak",
    bahasa: "Batak",
    imgUrl: "URL_RUMAH_TRADISIONAL_SUMUT",
    coordinates: [98.6669, 3.5952], // Sumatera Utara
  },
  {
    name: "Sumatera Barat",
    title: "Datuk",
    rumah: "Gadang",
    pakaian: "Bundo Kanduang",
    musik: "Saluang, Talempong",
    tari: "Tari Piring, Tari Payung",
    senjata: "Karih",
    bahasa: "Minangkabau",
    imgUrl: "URL_RUMAH_TRADISIONAL_SUMBAR",
    coordinates: [100.3691, -0.3054], // Sumatera Barat
  },
  {
    name: "Riau",
    title: "Datuk",
    rumah: "Selaso Jatuh Kembar",
    pakaian: "Melayu",
    musik: "Gambus, Kompang",
    tari: "Tari Zapin, Tari Makan Sirih",
    senjata: "Badik",
    bahasa: "Melayu",
    imgUrl: "URL_RUMAH_TRADISIONAL_RIAU",
    coordinates: [101.4477, 0.5333], // Riau
  },
  {
    name: "Jambi",
    title: "Datuk",
    rumah: "Panggung",
    pakaian: "Melayu",
    musik: "Gambus, Serampang",
    tari: "Tari Sekapur Sirih, Tari Rentak Besapih",
    senjata: "Keris",
    bahasa: "Melayu",
    imgUrl: "URL_RUMAH_TRADISIONAL_JAMBI",
    coordinates: [103.6145, -1.6106], // Jambi
  },
  {
    name: "Sumatera Selatan",
    title: "Sultan",
    rumah: "Limas",
    pakaian: "Aesan Gede",
    musik: "Tanjidor",
    tari: "Tari Gending Sriwijaya, Tari Tanggai",
    senjata: "Keris",
    bahasa: "Palembang",
    imgUrl: "URL_RUMAH_TRADISIONAL_SUMSEL",
    coordinates: [104.7458, -3.3194], // Sumatera Selatan
  },
  {
    name: "Bengkulu",
    title: "Depati",
    rumah: "Bubungan Lima",
    pakaian: "Melayu",
    musik: "Doll",
    tari: "Tari Andun, Tari Kejei",
    senjata: "Keris",
    bahasa: "Melayu",
    imgUrl: "URL_RUMAH_TRADISIONAL_BENGKULU",
    coordinates: [102.2655, -3.8004], // Bengkulu
  },
  {
    name: "Lampung",
    title: "Suttan",
    rumah: "Nuwou Sesat",
    pakaian: "Tapis",
    musik: "Gamelan",
    tari: "Tari Sembah, Tari Cangget",
    senjata: "Keris",
    bahasa: "Lampung",
    imgUrl: "URL_RUMAH_TRADISIONAL_LAMPUNG",
    coordinates: [105.258, -5.4497], // Lampung
  },
  {
    name: "DKI Jakarta",
    title: "Betawi",
    rumah: "Kebaya",
    pakaian: "Sadariah",
    musik: "Tanjidor",
    tari: "Tari Topeng, Tari Yapong",
    senjata: "Golok",
    bahasa: "Betawi",
    imgUrl: "URL_RUMAH_TRADISIONAL_DKI_JAKARTA",
    coordinates: [106.8456, -6.2088], // DKI Jakarta
  },
  {
    name: "Jawa Barat",
    title: "Prabu",
    rumah: "Kasepuhan",
    pakaian: "Kebaya Sunda",
    musik: "Angklung",
    tari: "Tari Jaipong, Tari Merak",
    senjata: "Kujang",
    bahasa: "Sunda",
    imgUrl: "URL_RUMAH_TRADISIONAL_JABAR",
    coordinates: [107.6191, -6.9175], // Jawa Barat
  },
  {
    name: "Jawa Tengah",
    title: "Adipati",
    rumah: "Joglo",
    pakaian: "Kebaya Jawa",
    musik: "Gamelan",
    tari: "Tari Gambyong, Tari Bedhaya",
    senjata: "Keris",
    bahasa: "Jawa",
    imgUrl: "URL_RUMAH_TRADISIONAL_JATENG",
    coordinates: [110.4126, -6.9666], // Jawa Tengah
  },
  {
    name: "DI Yogyakarta",
    title: "Sultan",
    rumah: "Joglo",
    pakaian: "Kebaya Jawa",
    musik: "Gamelan",
    tari: "Tari Srimpi, Tari Bedhaya",
    senjata: "Keris",
    bahasa: "Jawa",
    imgUrl: "URL_RUMAH_TRADISIONAL_DIY",
    coordinates: [110.3671, -7.8014], // DI Yogyakarta
  },
  {
    name: "Jawa Timur",
    title: "Raden",
    rumah: "Joglo",
    pakaian: "Kebaya Jawa",
    musik: "Gamelan",
    tari: "Tari Reog, Tari Gandrung",
    senjata: "Keris",
    bahasa: "Jawa",
    imgUrl: "URL_RUMAH_TRADISIONAL_JATIM",
    coordinates: [112.7521, -7.2575], // Jawa Timur
  },
  {
    name: "Banten",
    title: "Sultan",
    rumah: "Baduy",
    pakaian: "Kebaya Sunda",
    musik: "Angklung",
    tari: "Tari Cokek, Tari Bendrong Lesung",
    senjata: "Kujang",
    bahasa: "Sunda",
    imgUrl: "URL_RUMAH_TRADISIONAL_BANTEN",
    coordinates: [106.1501, -6.1111], // Banten
  },
  {
    name: "Bali",
    title: "Dewa",
    rumah: "Gapura Candi Bentar",
    pakaian: "Kebaya Bali",
    musik: "Gamelan Bali",
    tari: "Tari Kecak, Tari Legong",
    senjata: "Keris",
    bahasa: "Bali",
    imgUrl: "URL_RUMAH_TRADISIONAL_BALI",
    coordinates: [115.1889, -8.4095], // Bali
  },
  {
    name: "Nusa Tenggara Barat",
    title: "Raden",
    rumah: "Lumbung",
    pakaian: "Lambung",
    musik: "Gendang Beleq",
    tari: "Tari Gandrung, Tari Batik",
    senjata: "Keris",
    bahasa: "Sasak",
    imgUrl: "URL_RUMAH_TRADISIONAL_NTB",
    coordinates: [116.4194, -8.6529], // Nusa Tenggara Barat
  },
  {
    name: "Nusa Tenggara Timur",
    title: "Mosalaki",
    rumah: "Sao Ata Mosa Lakitana",
    pakaian: "Tenun Ikat",
    musik: "Sasando",
    tari: "Tari Caci, Tari Dolo-Dolo",
    senjata: "Keris",
    bahasa: "Nusa Tenggara",
    imgUrl: "URL_RUMAH_TRADISIONAL_NTT",
    coordinates: [123.5938, -10.1772], // Nusa Tenggara Timur
  },
  {
    name: "Kalimantan Barat",
    title: "Panembahan",
    rumah: "Panjang",
    pakaian: "King Bibinge",
    musik: "Tingkilan",
    tari: "Tari Monong, Tari Zapin",
    senjata: "Mandau",
    bahasa: "Dayak",
    imgUrl: "URL_RUMAH_TRADISIONAL_KALBAR",
    coordinates: [109.3394, -0.0263], // Kalimantan Barat
  },
  {
    name: "Kalimantan Tengah",
    title: "Damang",
    rumah: "Betang",
    pakaian: "King Bibinge",
    musik: "Gamelan",
    tari: "Tari Tambun, Tari Bungai",
    senjata: "Mandau",
    bahasa: "Dayak",
    imgUrl: "URL_RUMAH_TRADISIONAL_KALTENG",
    coordinates: [113.923, -1.6815], // Kalimantan Tengah
  },
  {
    name: "Kalimantan Selatan",
    title: "Sultan",
    rumah: "Bubungan Tinggi",
    pakaian: "Bagajah Gamuling Baular Lulut",
    musik: "Panting",
    tari: "Tari Baksa Kembang, Tari Radap Rahayu",
    senjata: "Keris",
    bahasa: "Banjar",
    imgUrl: "URL_RUMAH_TRADISIONAL_KALSEL",
    coordinates: [114.5919, -3.3186], // Kalimantan Selatan
  },
  {
    name: "Kalimantan Timur",
    title: "Sultan",
    rumah: "Lamin",
    pakaian: "Sapei Sapaq",
    musik: "Sampek",
    tari: "Tari Gong, Tari Gantar",
    senjata: "Mandau",
    bahasa: "Dayak",
    imgUrl: "URL_RUMAH_TRADISIONAL_KALTIM",
    coordinates: [117.1838, 0.5306], // Kalimantan Timur
  },
  {
    name: "Kalimantan Utara",
    title: "Tidung",
    rumah: "Baloy",
    pakaian: "Tidung",
    musik: "Bunai",
    tari: "Tari Jepen, Tari Gong",
    senjata: "Mandau",
    bahasa: "Tidung",
    imgUrl: "URL_RUMAH_TRADISIONAL_KALTARA",
    coordinates: [116.0028, 3.3274], // Kalimantan Utara
  },
  {
    name: "Sulawesi Utara",
    title: "Dotu",
    rumah: "Wale",
    pakaian: "Laku Tepu",
    musik: "Kolintang",
    tari: "Tari Maengket, Tari Katrili",
    senjata: "Keris",
    bahasa: "Manado",
    imgUrl: "URL_RUMAH_TRADISIONAL_SULUT",
    coordinates: [124.8473, 1.4748], // Sulawesi Utara
  },
  {
    name: "Sulawesi Tengah",
    title: "Madika",
    rumah: "Tambi",
    pakaian: "Bomba",
    musik: "Ganda",
    tari: "Tari Dero, Tari Pontanu",
    senjata: "Keris",
    bahasa: "Kaili",
    imgUrl: "URL_RUMAH_TRADISIONAL_SULTENG",
    coordinates: [121.4456, -0.8987], // Sulawesi Tengah
  },
  {
    name: "Sulawesi Selatan",
    title: "Karaeng",
    rumah: "Tongkonan",
    pakaian: "Baju Bodo",
    musik: "Gandrang Bulo",
    tari: "Tari Paduppa Bosara, Tari Kipas",
    senjata: "Badik",
    bahasa: "Makassar",
    imgUrl: "URL_RUMAH_TRADISIONAL_SULSEL",
    coordinates: [119.4327, -5.1477], // Sulawesi Selatan
  },
  {
    name: "Sulawesi Tenggara",
    title: "Sangia",
    rumah: "Laikas",
    pakaian: "Baju Wolio",
    musik: "Gamelan",
    tari: "Tari Lulo, Tari Balumpa",
    senjata: "Keris",
    bahasa: "Tolaki",
    imgUrl: "URL_RUMAH_TRADISIONAL_SULTRA",
    coordinates: [122.5189, -4.1299], // Sulawesi Tenggara
  },
  {
    name: "Gorontalo",
    title: "Bate",
    rumah: "Dulohupa",
    pakaian: "Biliu",
    musik: "Polopalo",
    tari: "Tari Saronde, Tari Dana-Dana",
    senjata: "Peda",
    bahasa: "Gorontalo",
    imgUrl: "URL_RUMAH_TRADISIONAL_GORONTALO",
    coordinates: [123.0707, 0.5479], // Gorontalo
  },
  {
    name: "Sulawesi Barat",
    title: "Maradika",
    rumah: "Boyang",
    pakaian: "Lipa Saqbe Mandar",
    musik: "Gendang",
    tari: "Tari Pattuqduq",
    senjata: "Kris",
    bahasa: "Mandar",
    imgUrl: "URL_RUMAH_TRADISIONAL_SULBAR",
    coordinates: [119.3637, -2.6787], // Sulawesi Barat
  },
  {
    name: "Maluku",
    title: "Upu",
    rumah: "Baileo",
    pakaian: "Baniang Putih",
    musik: "Totobuang",
    tari: "Tari Cakalele, Tari Lenso",
    senjata: "Parang",
    bahasa: "Ambon",
    imgUrl: "URL_RUMAH_TRADISIONAL_MALUKU",
    coordinates: [128.1903, -3.6558], // Maluku
  },
  {
    name: "Maluku Utara",
    title: "Jojau",
    rumah: "Sasadu",
    pakaian: "Manteren Lamo",
    musik: "Tifa",
    tari: "Tari Tide-Tide, Tari Salai Jin",
    senjata: "Parang",
    bahasa: "Ternate",
    imgUrl: "URL_RUMAH_TRADISIONAL_MALUT",
    coordinates: [127.796, 0.8], // Maluku Utara
  },
  {
    name: "Papua",
    title: "Ondofolo",
    rumah: "Honai",
    pakaian: "Koteka",
    musik: "Tifa",
    tari: "Tari Yospan, Tari Selamat Datang",
    senjata: "Busur dan Panah",
    bahasa: "Papua",
    imgUrl: "URL_RUMAH_TRADISIONAL_PAPUA",
    coordinates: [140.0168, -2.5337], // Papua
  },
  {
    name: "Papua Barat",
    title: "Mananwir",
    rumah: "Mod Aki Aksa",
    pakaian: "Serui",
    musik: "Tifa",
    tari: "Tari Suanggi, Tari Perang",
    senjata: "Parang",
    bahasa: "Papua",
    imgUrl: "URL_RUMAH_TRADISIONAL_PAPUA_BARAT",
    coordinates: [132.2467, -1.3361], // Papua Barat
  },
  {
    name: "Papua Selatan",
    title: "Mananwir",
    rumah: "Karapao",
    pakaian: "Yakal",
    musik: "Tifa",
    tari: "Tari Karapao, Tari Wor",
    senjata: "Busur dan Panah",
    bahasa: "Papua",
    imgUrl: "URL_RUMAH_TRADISIONAL_PAPUA_SELATAN",
    coordinates: [138.4534, -6.1355], // Papua Selatan
  },
  {
    name: "Papua Tengah",
    title: "Mananwir",
    rumah: "Ebe",
    pakaian: "Yakal",
    musik: "Tifa",
    tari: "Tari Karapao, Tari Wor",
    senjata: "Busur dan Panah",
    bahasa: "Papua",
    imgUrl: "URL_RUMAH_TRADISIONAL_PAPUA_TENGAH",
    coordinates: [137.4506, -4.1299], // Papua Tengah
  },
  {
    name: "Papua Pegunungan",
    title: "Mananwir",
    rumah: "Ebe",
    pakaian: "Yakal",
    musik: "Tifa",
    tari: "Tari Karapao, Tari Wor",
    senjata: "Busur dan Panah",
    bahasa: "Papua",
    imgUrl: "URL_RUMAH_TRADISIONAL_PAPUA_PEGUNUNGAN",
    coordinates: [140.0168, -4.6831], // Papua Pegunungan
  },
  {
    name: "Papua Barat Daya",
    title: "Mananwir",
    rumah: "Karapao",
    pakaian: "Yakal",
    musik: "Tifa",
    tari: "Tari Karapao, Tari Wor",
    senjata: "Busur dan Panah",
    bahasa: "Papua",
    imgUrl: "URL_RUMAH_TRADISIONAL_PAPUA_BARAT_DAYA",
    coordinates: [131.5272, -0.9243], // Papua Barat Daya
  },
];

export default data;
